# Generated by Django 4.2.7 on 2024-12-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('number', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
