# Generated by Django 4.2.7 on 2024-12-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
