# Generated by Django 4.2.7 on 2024-12-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_member_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.BooleanField(),
        ),
    ]
