# Generated by Django 4.2.7 on 2024-12-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_member_data_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
