# Generated by Django 5.1.4 on 2025-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_member_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(max_length=15, verbose_name='Статус(активен/уволен)'),
        ),
    ]
